namespace WoW.Two.Sdk.Backend.Beta.Media.Captions.Parsers;

/// <summary>
/// Parses caption text into segments or tracks by selecting a format-specific parser.
/// Detection follows <see cref="CaptionFormatMapper"/>; leaf parsers retain their own failure behavior.
/// </summary>
/// <param name="vtt">The WebVTT parser.</param>
/// <param name="srt">The SubRip parser.</param>
/// <param name="ttml">The TTML/DFXP parser.</param>
/// <param name="json3">The YouTube json3 parser.</param>
public sealed class CompositeCaptionParser(
    IVttCaptionParser vtt,
    ISrtCaptionParser srt,
    ITtmlCaptionParser ttml,
    IJson3CaptionParser json3) : ICaptionParser
{
    private readonly IVttCaptionParser _vtt = vtt ?? throw new ArgumentNullException(nameof(vtt));
    private readonly ISrtCaptionParser _srt = srt ?? throw new ArgumentNullException(nameof(srt));
    private readonly ITtmlCaptionParser _ttml = ttml ?? throw new ArgumentNullException(nameof(ttml));
    private readonly IJson3CaptionParser _json3 = json3 ?? throw new ArgumentNullException(nameof(json3));

    /// <inheritdoc />
    public IReadOnlyList<CaptionSegment> Parse(string content, CaptionFormat format) => format switch
    {
        CaptionFormat.WebVtt => _vtt.Parse(content),
        CaptionFormat.SubRip => _srt.Parse(content),
        CaptionFormat.Ttml => _ttml.Parse(content),
        CaptionFormat.YouTubeJson3 => _json3.Parse(content),
        _ => [],
    };

    /// <inheritdoc />
    public IReadOnlyList<CaptionSegment> Parse(string content)
        => CaptionFormatMapper.TryDetect(content, out var format) ? Parse(content, format) : [];

    /// <inheritdoc />
    public bool TryParse(string content, out IReadOnlyList<CaptionSegment> segments)
    {
        if (CaptionFormatMapper.TryDetect(content, out var format))
        {
            segments = Parse(content, format);
            return true;
        }

        segments = [];
        return false;
    }

    /// <inheritdoc />
    public CaptionTrack ParseTrack(string content, string language, bool isAutoGenerated, CaptionFormat? format = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(language);

        var segments = format is { } known
            ? Parse(content, known)
            : Parse(content);

        return new CaptionTrack
        {
            Language = language,
            IsAutoGenerated = isAutoGenerated,
            Segments = segments,
        };
    }
}
