namespace WoW.Two.Sdk.Backend.Beta.Media.Captions.Parsers;

/// <summary>
/// Defines caption text parsing into segments and tracks across WebVTT, SubRip, TTML and YouTube json3.
/// </summary>
/// <remarks>
/// Automatic selection uses the first matching heuristic: WEBVTT header, a JSON-looking document containing
/// an events key, an XML-looking document containing a TTML marker, comma-decimal cue timing, then an arrow marker.
/// A JSON-looking or XML-looking document without its marker is unrecognized; later heuristics are not attempted.
/// Ambiguous input is not probed against multiple parsers. Null, blank and unrecognized input yields no segments.
/// Recognized input inherits its leaf parser's skips, empty results and exceptions; detection is not validation.
/// </remarks>
public interface ICaptionParser
{
    /// <summary>Parses <paramref name="content"/> using the explicitly specified <paramref name="format"/>.</summary>
    /// <param name="content">The caption document text.</param>
    /// <param name="format">The known format of the content.</param>
    /// <returns>The parsed segments in document order, or an empty list for an unsupported format value.</returns>
    /// <remarks>Malformed or incomplete input follows the selected leaf parser's documented behavior.</remarks>
    IReadOnlyList<CaptionSegment> Parse(string content, CaptionFormat format);

    /// <summary>Detects the format of <paramref name="content"/> and parses it; returns empty when the format is unrecognized.</summary>
    /// <param name="content">The caption document text.</param>
    /// <returns>The parsed segments, or an empty list when the format cannot be detected.</returns>
    IReadOnlyList<CaptionSegment> Parse(string content);

    /// <summary>Detects and parses <paramref name="content"/>, reporting whether the format was recognized.</summary>
    /// <param name="content">The caption document text.</param>
    /// <param name="segments">The parsed segments, or an empty list when detection fails.</param>
    /// <returns><see langword="true"/> when the format was recognized; otherwise <see langword="false"/>.</returns>
    /// <remarks>
    /// A true result may contain no segments or only the accepted cues. Leaf parser exceptions propagate;
    /// this method does not guarantee non-throwing parsing or document validity.
    /// </remarks>
    bool TryParse(string content, out IReadOnlyList<CaptionSegment> segments);

    /// <summary>
    /// Parses <paramref name="content"/> into a language-tagged <see cref="CaptionTrack"/>. When
    /// <paramref name="format"/> is <see langword="null"/> the format is auto-detected.
    /// </summary>
    /// <param name="content">The caption document text.</param>
    /// <param name="language">The BCP-47 language code to tag the track with.</param>
    /// <param name="isAutoGenerated">Whether the track is machine-generated.</param>
    /// <param name="format">The known format, or <see langword="null"/> to auto-detect.</param>
    /// <returns>A track carrying the parsed segments (empty segments when detection/parse yields nothing).</returns>
    /// <exception cref="ArgumentException">The language is empty or whitespace.</exception>
    /// <exception cref="ArgumentNullException">The language is null.</exception>
    CaptionTrack ParseTrack(string content, string language, bool isAutoGenerated, CaptionFormat? format = null);
}
