namespace WoW.Two.Sdk.Backend.Beta.Identity.Mfa.Totp;

/// <summary>Holds the TOTP parameters an authenticator app has to agree on (RFC 6238).</summary>
public sealed record TotpOptions
{
    /// <summary>Gets the time step in seconds. RFC 6238 default is 30.</summary>
    public int StepSeconds { get; set; } = 30;

    /// <summary>Gets the code length in digits. Most authenticator apps use 6; some issuers use 8.</summary>
    public int Digits { get; set; } = 6;

    /// <summary>Gets how many steps either side of now a code still verifies against.</summary>
    public int VerificationSteps { get; set; } = 1;

    /// <summary>Gets the secret length in bytes generated by <c>GenerateSecret</c>. 20 bytes is 160 bits.</summary>
    public int SecretBytes { get; set; } = 20;
}
