namespace WoW.Two.Sdk.Backend.Beta.Media.Captions;

/// <summary>
/// A format-aware facade over the per-format caption parsers (WebVTT, SubRip, TTML, YouTube json3).
/// Use this when the input format is not known ahead of time or varies — it detects and dispatches; use
/// a concrete parser (<see cref="IVttCaptionParser"/>, …) when the format is fixed.
/// </summary>
public interface ICaptionParser
{
    /// <summary>Parses <paramref name="content"/> using the explicitly specified <paramref name="format"/>.</summary>
    /// <param name="content">The caption document text.</param>
    /// <param name="format">The known format of the content.</param>
    /// <returns>The parsed segments in document order.</returns>
    IReadOnlyList<CaptionSegment> Parse(string content, CaptionFormat format);

    /// <summary>Detects the format of <paramref name="content"/> and parses it; returns empty when the format is unrecognized.</summary>
    /// <param name="content">The caption document text.</param>
    /// <returns>The parsed segments, or an empty list when the format cannot be detected.</returns>
    IReadOnlyList<CaptionSegment> Parse(string content);

    /// <summary>Detects and parses <paramref name="content"/>, reporting whether the format was recognized.</summary>
    /// <param name="content">The caption document text.</param>
    /// <param name="segments">The parsed segments, or an empty list when detection fails.</param>
    /// <returns><see langword="true"/> when the format was detected and parsed; otherwise <see langword="false"/>.</returns>
    bool TryParse(string content, out IReadOnlyList<CaptionSegment> segments);

    /// <summary>
    /// Parses <paramref name="content"/> into a language-tagged <see cref="CaptionTrack"/>. When
    /// <paramref name="format"/> is <see langword="null"/> the format is auto-detected.
    /// </summary>
    /// <param name="content">The caption document text.</param>
    /// <param name="language">The BCP-47 language code to tag the track with.</param>
    /// <param name="isAutoGenerated">Whether the track is machine-generated.</param>
    /// <param name="format">The known format, or <see langword="null"/> to auto-detect.</param>
    /// <returns>A track carrying the parsed segments (empty segments when detection/parse yields nothing).</returns>
    CaptionTrack ParseTrack(string content, string language, bool isAutoGenerated, CaptionFormat? format = null);
}
