namespace WoW.Two.Sdk.Backend.Beta.Media.Captions;

/// <summary>Represents a caption track for a single language — an ordered set of timed segments.</summary>
public sealed record CaptionTrack
{
    /// <summary>Gets the BCP-47 language code of the caption track.</summary>
    public required string Language { get; init; }

    /// <summary>Gets whether the track is machine-generated rather than human-authored.</summary>
    public required bool IsAutoGenerated { get; init; }

    /// <summary>Gets the ordered collection of timed caption segments.</summary>
    public required IReadOnlyList<CaptionSegment> Segments { get; init; }
}
