namespace WoW.Two.Sdk.Backend.Beta.Media.Captions;

/// <summary>
/// Default <see cref="ICaptionParser"/> facade — detects the caption format via
/// <see cref="CaptionFormatDetector"/> and dispatches to the matching per-format parser. Stateless and
/// thread-safe; composed of the four singleton per-format parsers.
/// </summary>
public sealed class CompositeCaptionParser : ICaptionParser
{
    private readonly IVttCaptionParser _vtt;
    private readonly ISrtCaptionParser _srt;
    private readonly ITtmlCaptionParser _ttml;
    private readonly IJson3CaptionParser _json3;

    /// <summary>Creates the facade over the four per-format parsers.</summary>
    /// <param name="vtt">The WebVTT parser.</param>
    /// <param name="srt">The SubRip parser.</param>
    /// <param name="ttml">The TTML/DFXP parser.</param>
    /// <param name="json3">The YouTube json3 parser.</param>
    public CompositeCaptionParser(IVttCaptionParser vtt, ISrtCaptionParser srt, ITtmlCaptionParser ttml, IJson3CaptionParser json3)
    {
        ArgumentNullException.ThrowIfNull(vtt);
        ArgumentNullException.ThrowIfNull(srt);
        ArgumentNullException.ThrowIfNull(ttml);
        ArgumentNullException.ThrowIfNull(json3);
        _vtt = vtt;
        _srt = srt;
        _ttml = ttml;
        _json3 = json3;
    }

    /// <inheritdoc />
    public IReadOnlyList<CaptionSegment> Parse(string content, CaptionFormat format) => format switch
    {
        CaptionFormat.WebVtt => _vtt.Parse(content),
        CaptionFormat.SubRip => _srt.Parse(content),
        CaptionFormat.Ttml => _ttml.Parse(content),
        CaptionFormat.YouTubeJson3 => _json3.Parse(content),
        _ => [],
    };

    /// <inheritdoc />
    public IReadOnlyList<CaptionSegment> Parse(string content)
        => CaptionFormatDetector.TryDetect(content, out var format) ? Parse(content, format) : [];

    /// <inheritdoc />
    public bool TryParse(string content, out IReadOnlyList<CaptionSegment> segments)
    {
        if (CaptionFormatDetector.TryDetect(content, out var format))
        {
            segments = Parse(content, format);
            return true;
        }

        segments = [];
        return false;
    }

    /// <inheritdoc />
    public CaptionTrack ParseTrack(string content, string language, bool isAutoGenerated, CaptionFormat? format = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(language);

        var segments = format is { } known
            ? Parse(content, known)
            : Parse(content);

        return new CaptionTrack
        {
            Language = language,
            IsAutoGenerated = isAutoGenerated,
            Segments = segments,
        };
    }
}
